<a href="https://colab.research.google.com/github/priyanshulink/NumPy/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#  create array in python

import numpy as np

**Basic Array creation**

In [ ]:
arry = np.array([1,2,3,4])

array([1, 2, 3, 4])

In [ ]:
"""vector - something that is created single one dimentional.
   example - arr = np.array([1,2,3,4])
"""
"""matrix - have multiple dimentional
examaple arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
"""

"""
but list not support multidimentional list.
"""
np.array([[1,2,3],[4,5,6],[7,8,9]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

**Array Generation Function**

In [ ]:
# arange is also work like loop
arr = np.arange(1,11) #this will generate array form 1 to 10
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
arr = np.zeros(6) # this will give zero
print(arr)

print("how do i generate matrix of zero")

arrM = np.zeros((6,6)) # this means 6 rows and 6 column
print(arrM)

[0. 0. 0. 0. 0. 0.]
how do i generate matrix of zero
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [ ]:
arr = np.ones(6)
print(arr)

[1. 1. 1. 1. 1. 1.]


In [ ]:
arr = np.ones((6,6))
print(arr)

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [ ]:
#Linear space is also called lenspace

arr = np.linspace(1,5,2)
print(arr)

[1. 5.]


**Random generation function**

In [4]:
# rand() - it generate decimal number between 0 and 1
arr = np.random.rand(5)
print(arr)

[0.40845993 0.69721553 0.57546253 0.75203064 0.34867453]


In [5]:
# randn()  - it generate decimal number between -3 to 3
arr = np.random.randn(5)
print(arr)

[-0.0298185  -2.07596165  0.23768679 -0.75560015 -0.07399356]


In [8]:
# randint()  - it generate random integer
arr = np.random.randint(1,5)
print(arr)
arr1 = np.random.randint(1,10,5) #this will give 5 integer between 1 to 10
print(arr1)

4
[9 1 9 1 4]


In [9]:
# random 2D arrary
arr = np.random.randint(1,10,(3,4))
print(arr)

[[9 8 4 9]
 [3 2 6 8]
 [5 4 4 4]]


In [11]:
# choice()
arr = np.random.choice([10,20,30,40,50]) #this will give any number that is in the list
print(arr)

40


In [2]:
""" seed()

Think of seed() like a bookmark 📖

Imagine a book with thousands of random numbers.

seed(10) → Start reading from page 10.
seed(20) → Start reading from page 20.
seed(100) → Start reading from page 100.

The seed is not the output. It just decides where the random number generator starts
"""

np.random.seed(20)

print(np.random.randint(1, 100))
print(np.random.randint(1, 100))
print(np.random.randint(1, 100))


91
16
96


**Array Attribute**


In [3]:
arr = np.array([[10, 20, 30],
                [40, 50, 60]])
print(arr)

[[10 20 30]
 [40 50 60]]


In [7]:
print(arr.shape) # tell you number of row and col.

(2, 3)


In [8]:
print(arr.size) # tell you total number of element

6


In [9]:
print(arr.dtype) # tell you data type of element

int64


In [10]:
print(arr.ndim) # tell how many dimention array has

2


In [11]:
print(arr.itemsize) # tell you how many byte one element occupies

8


In [12]:
print(arr.nbytes) # tell total memenory used by array

48


In [13]:
print(arr.T) # it swap row and column

[[10 40]
 [20 50]
 [30 60]]


In [14]:
for i in arr.flat: # flat - is used to print each element of array
  print(i)

10
20
30
40
50
60


**Array Methods*

In [15]:
arr = np.arange(1,30)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29]


In [17]:
print(arr.min()) #give min element in array

1


In [18]:
print(arr.max()) # give max element in array

29


In [19]:
print(arr.sum()) # return sum of element

435


In [20]:
print(np.sum(arr,axis = 0)) # this will return sum of all  col = 0

435


In [21]:
print(arr.mean()) # retrun average

15.0


In [22]:
arr.std()

np.float64(8.366600265340756)

In [23]:
print(arr.argmax()) #return largest element index

28


In [24]:
print(arr.argmin()) # return smallest elemnt index

0


In [31]:
arr = np.arange(1,31)
new_arr = arr.reshape(2,15)
print(new_arr)

[[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23 24 25 26 27 28 29 30]]


In [33]:
print(new_arr.flatten())

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30]
