<a href="https://colab.research.google.com/github/priyanshulink/NumPy/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
#  create array in python

import numpy as np

**Basic Array creation**

In [ ]:
arry = np.array([1,2,3,4])

array([1, 2, 3, 4])

In [ ]:
"""vector - something that is created single one dimentional.
   example - arr = np.array([1,2,3,4])
"""
"""matrix - have multiple dimentional
examaple arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
"""

"""
but list not support multidimentional list.
"""
np.array([[1,2,3],[4,5,6],[7,8,9]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

**Array Generation Function**

In [ ]:
# arange is also work like loop
arr = np.arange(1,11) #this will generate array form 1 to 10
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
arr = np.zeros(6) # this will give zero
print(arr)

print("how do i generate matrix of zero")

arrM = np.zeros((6,6)) # this means 6 rows and 6 column
print(arrM)

[0. 0. 0. 0. 0. 0.]
how do i generate matrix of zero
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [ ]:
arr = np.ones(6)
print(arr)

[1. 1. 1. 1. 1. 1.]


In [ ]:
arr = np.ones((6,6))
print(arr)

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [3]:
#Linear space is also called lenspace

arr = np.linspace(1,5,2)
print(arr)

[1. 5.]


**Random generation function**