<a href="https://colab.research.google.com/github/priyanshulink/NumPy/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
#  create array in python

import numpy as np

**Basic Array creation**

In [ ]:
arry = np.array([1,2,3,4])

array([1, 2, 3, 4])

In [ ]:
"""vector - something that is created single one dimentional.
   example - arr = np.array([1,2,3,4])
"""
"""matrix - have multiple dimentional
examaple arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
"""

"""
but list not support multidimentional list.
"""
np.array([[1,2,3],[4,5,6],[7,8,9]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

**Array Generation Function**

In [ ]:
# arange is also work like loop
arr = np.arange(1,11) #this will generate array form 1 to 10
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
arr = np.zeros(6) # this will give zero
print(arr)

print("how do i generate matrix of zero")

arrM = np.zeros((6,6)) # this means 6 rows and 6 column
print(arrM)

[0. 0. 0. 0. 0. 0.]
how do i generate matrix of zero
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [ ]:
arr = np.ones(6)
print(arr)

[1. 1. 1. 1. 1. 1.]


In [ ]:
arr = np.ones((6,6))
print(arr)

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [ ]:
#Linear space is also called lenspace

arr = np.linspace(1,5,2)
print(arr)

[1. 5.]


**Random generation function**

In [4]:
# rand() - it generate decimal number between 0 and 1
arr = np.random.rand(5)
print(arr)

[0.40845993 0.69721553 0.57546253 0.75203064 0.34867453]


In [5]:
# randn()  - it generate decimal number between -3 to 3
arr = np.random.randn(5)
print(arr)

[-0.0298185  -2.07596165  0.23768679 -0.75560015 -0.07399356]


In [8]:
# randint()  - it generate random integer
arr = np.random.randint(1,5)
print(arr)
arr1 = np.random.randint(1,10,5) #this will give 5 integer between 1 to 10
print(arr1)

4
[9 1 9 1 4]


In [9]:
# random 2D arrary
arr = np.random.randint(1,10,(3,4))
print(arr)

[[9 8 4 9]
 [3 2 6 8]
 [5 4 4 4]]


In [11]:
# choice()
arr = np.random.choice([10,20,30,40,50]) #this will give any number that is in the list
print(arr)

40


In [2]:
""" seed()

Think of seed() like a bookmark 📖

Imagine a book with thousands of random numbers.

seed(10) → Start reading from page 10.
seed(20) → Start reading from page 20.
seed(100) → Start reading from page 100.

The seed is not the output. It just decides where the random number generator starts
"""

np.random.seed(20)

print(np.random.randint(1, 100))
print(np.random.randint(1, 100))
print(np.random.randint(1, 100))


91
16
96


**Array Attribute**


In [3]:
arr = np.array([[10, 20, 30],
                [40, 50, 60]])
print(arr)

[[10 20 30]
 [40 50 60]]


In [7]:
print(arr.shape) # tell you number of row and col.

(2, 3)


In [8]:
print(arr.size) # tell you total number of element

6


In [9]:
print(arr.dtype) # tell you data type of element

int64


In [10]:
print(arr.ndim) # tell how many dimention array has

2


In [11]:
print(arr.itemsize) # tell you how many byte one element occupies

8


In [12]:
print(arr.nbytes) # tell total memenory used by array

48


In [13]:
print(arr.T) # it swap row and column

[[10 40]
 [20 50]
 [30 60]]


In [14]:
for i in arr.flat: # flat - is used to print each element of array
  print(i)

10
20
30
40
50
60


**Array Methods*

In [15]:
arr = np.arange(1,30)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29]


In [17]:
print(arr.min()) #give min element in array

1


In [18]:
print(arr.max()) # give max element in array

29


In [19]:
print(arr.sum()) # return sum of element

435


In [20]:
print(np.sum(arr,axis = 0)) # this will return sum of all  col = 0

435


In [21]:
print(arr.mean()) # retrun average

15.0


In [22]:
arr.std()

np.float64(8.366600265340756)

In [23]:
print(arr.argmax()) #return largest element index

28


In [24]:
print(arr.argmin()) # return smallest elemnt index

0


In [31]:
arr = np.arange(1,31)
new_arr = arr.reshape(2,15)
print(new_arr)

[[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23 24 25 26 27 28 29 30]]


In [33]:
print(new_arr.flatten())

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30]


**Numpy indexing and sclicing matrix**

In [34]:
arr = np.arange(1,31).reshape(6,5)
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]


In [38]:
print(arr[3: ,3:]) #sclicing of matrix

[[19 20]
 [24 25]
 [29 30]]


In [39]:
arr[0]

array([1, 2, 3, 4, 5])

In [41]:
print(arr[0,0])

1


In [5]:
# Boolean Indexing
arr = np.arange(11,21)
bool_index = arr % 2 == 0

arr = arr[bool_index]

print(bool_index)
print(arr)

[False  True False  True False  True False  True False  True]
[12 14 16 18 20]


**Array Operation**

In [7]:
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])

In [8]:
# Addition
print(a+b)

[ 7  9 11 13 15]


In [9]:
# Subtraction
print(a-b)

[-5 -5 -5 -5 -5]


In [10]:
# Multiplication
print(a*b)

[ 6 14 24 36 50]


In [11]:
#division
print(a/b)

[0.16666667 0.28571429 0.375      0.44444444 0.5       ]


In [12]:
print(a**b)

[      1     128    6561  262144 9765625]


**Broadcasting**

In [15]:
l = [10,20,30,40]
arr = np.array(l)
# we have to add 10 in each element
for i in l:
  print(i+10)

# same thing by broadcasting
print(arr+10)

20
30
40
50
[20 30 40 50]


**Deep Copy and Sallow Copy**

In [18]:
"""
Sallow copy-
         we can make another notebook that reference to the same

         arr ----------┐
                       │
                       ▼
                 [10 20 30]
                       ▲
                       │
         copy ---------┘
  if we write something in copy original also change they have same notebook
"""
arr = np.array([10,20,30,40,50])
new_arr = arr.view()
# for sallow copy " .view() " is used
new_arr[0] = 100

print(new_arr) # this is copy array

#original array
print(arr)


[100  20  30  40  50]
[100  20  30  40  50]


In [19]:
"""
Deep Copy -
      You make a new notebook.

      Original ------> [Notebook A]

      Copied --------> [Notebook B]

    Changing Notebook B does not affect Notebook A.

  """

arr = np.array([10, 20, 30])
copy_arr = arr.copy()
# for deep copy " .copy() " is used
copy_arr[0] = 100

print("Original:", arr)
print("Copy    :", copy_arr)

Original: [10 20 30]
Copy    : [100  20  30]


**Matrix Operation**

In [20]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

In [22]:
# Multipliaction
print(a @ b)
# or
c = np.dot(a,b)
print(c)

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [23]:
# Transpose
print(a.T)

[[1 3]
 [2 4]]


**Advanced matrix Manipulation**


*   Stacking



In [24]:
# Stacking - combine tow are more array into a singal array
# stacking function

#vartical stacking

a = np.array([1,2,3])
b = np.array([4,5,6])

c = np.vstack((a,b))
print(c)

[[1 2 3]
 [4 5 6]]


In [25]:
# Horizontal stacking

a = np.array([1,2,3])
b = np.array([4,5,6])

c = np.hstack((a,b))
print(c)

[1 2 3 4 5 6]


In [26]:
# Column Stacking - this convert 1 D array into column
print(np.column_stack((a,b)))

[[1 4]
 [2 5]
 [3 6]]


In [28]:
# Stacking - unlike hstack, vstack and stack() create new axis
print(np.stack((a,b),axis = 1))

[[1 4]
 [2 5]
 [3 6]]


**spliting array**

In [30]:
# np.split() - it split into two equal size part (most importent)
arr = np.array([10,20,30,40,50,60])
new_arr = np.split(arr,2)
print(new_arr)

[array([10, 20, 30]), array([40, 50, 60])]


In [31]:
# np.array_split() - thy can split unevenly
arr = np.array([10,20,30,40,50,60])
new_arr = np.array_split(arr,3)
print(new_arr)

[array([10, 20]), array([30, 40]), array([50, 60])]


In [33]:
# np.hsplit -
arr = np.array([[10,20,30,50],[40,50,60,70]])
new_arr = np.hsplit(arr,2)
print(new_arr)

[array([[10, 20],
       [40, 50]]), array([[30, 50],
       [60, 70]])]


In [34]:
# np.vsplit
arr = np.array([[10,20,30,50],[40,50,60,70]])
new_arr = np.vsplit(arr,2)
print(new_arr)

[array([[10, 20, 30, 50]]), array([[40, 50, 60, 70]])]
